### PR TITLE
Fix for breaking change in `karma@0.13.x`

### PR DESCRIPTION
**Pull request by marshall007**
Fixes breaking change introduces in `karma@0.13.x` (see #1 for details).

### CODE REVIEW

**Comment by marshall007** [comment]
If you want to maintain compatibility with <=0.12.x I think that would be possible. Let me know and I'll update the PR.

**Comment by wilsonjackson** [comment]
Thanks a bunch for your work on this. I really would like to support both 0.13.x and earlier versions, just so there don't have to be different versions of this plugin for different versions of karma — that's confusing.

**Comment by marshall007** [comment]
@wilsonjackson: nevermind, I was thinking we could just wrap the incoming value in `Q.resolve()` and always treat it like a promise for backwards-compatibility. The problem is if updated/newer plugins are relying on `0.13.x` behavior we will emit a promise and just break them instead of us.

Since this is a breaking change in `karma` I'd say its fine to not be backwards-compatible. Maybe throw a note at the top of the README warning `<0.13.x` users to stay on the old version of this plugin?

**Comment by wilsonjackson** [comment]
Fair enough, it would be better to release a compatible version than nothing at all. I really just wish the Karma team would implement an actual system for async plugins...

Thanks for the PR!

**Comment by marshall007** [comment]
@wilsonjackson agreed. No problem, cheers!

**Pull request merged**
